# tensor속성
* 축 개수 (rank): 3D tensor의 rank는 3 (ndim으로 확인 가능)
* shape : 각 축을 따라 얼마나 많은 차원이 있는지를 나타낸 파있너의 튜플(tuple)
* 데이터 타입: dtype에 저장

# scaler(0D tensor)
* ndim 속성 사용하면 넘파이 배열 축 개수 확인 가능 (ndim==0)
* rank : 텐서의 축 개수

In [1]:
import numpy as np
x=np.array(12)
x

array(12)

In [2]:
x.ndim

0

# vector(1D tensor)

In [3]:
x=np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [4]:
x.ndim

1

# matirx(2D tensor)
* 행 (row)
* 열 (column)

In [7]:
x=np.array([[1,2,3],
            [2,3,4],
            [3,4,5]])
x

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [8]:
x.ndim

2

# 3D tensor와 고차원 텐서
* 3D 텐서들을 하나로 합치면 4D 텐서를 만드는 식으로 이어진다
* 딥러닝에서는 보통 0D에서 4D까지의 텐서를 다룬다

In [10]:
x=np.array([[[1,2,3],
            [2,3,4],
            [3,4,5]],
            [[1,2,3],
            [2,3,4],
            [3,4,5]]])
x

array([[[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]],

       [[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]]])

# slicing 
[10:100] :11번째부터 101번째까지(101은 포함하지 않고)

In [13]:
from keras.datasets import mnist

(train_images, train_labels),(test_images, test_labels)=mnist.load_data()
print(train_images.ndim)
print(train_images.shape)
print(test_images.shape)
print(train_labels.ndim)
print(train_labels.shape)
print(test_labels.shape)

3
(60000, 28, 28)
(10000, 28, 28)
1
(60000,)
(10000,)


In [14]:
my_slice=train_images[10:100]
print(my_slice.shape)

(90, 28, 28)


In [19]:
my_slice2=my_slice[:,14:,14:] #오른쪽 아래 14*14픽셀 선택
my_slice2.shape

(90, 14, 14)

# image data
* 256x256 크기의 흑백 이미지에 대한 128개의 배치는 (128, 256,256,1)크기의 텐서에 저장
* 256x256 크기의 컬러 이미지에 대한 128개의 배치는 (128,256,256,3)크기의 텐서
* 이미지 텐서의 크기를 지정하는 방식 2가지
    - (텐서플로우에서 사용하는) 채널 마지막 (channel-last)방식 :(samples, height, width, color_depth)
    - (씨아노에서 사용하는) 채널 우선 (channel-first)방식 :(samples, coler_depth, height, width)
    - 케라스 프레임워크는 두 형식을 모두 지원한다

# 브로드캐스팅

1. 큰 텐서의 ndim에 맞도록 작은 텐서에 (브로드캐스팅 축이라고 부르는) 축이 추가된다
2. 작은 텐서가 새 축을 따라서 큰 텐서의 크기에 맞도록 반복됨

In [21]:
import numpy as np

x=np.random.random((64, 3,32,10))
y=np.random.random((32,10))

z=np.maximum(x,y)
z.shape

(64, 3, 32, 10)

# tensor 크기 변환

tensor.reshape()

In [23]:
x=np.array([[0.,1.],
           [2.,3.],
           [4.,5.]])
print(x.shape)
x=x.reshape((6,1))
x

(3, 2)


array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [26]:
# transposition
x=np.transpose(x)
print(x.shape)
x

(1, 6)


array([[0., 1., 2., 3., 4., 5.]])