# Numpy Basic

In [2]:
import numpy as np

## data type

array의 dtype을 본다. 

.astype()으로 datatype을 변환 가능

len(arr.shape) 를 통해서 차원의 갯수를 확인 할 수 있지만,  
아래와 같이 ndim을 통해 차원 수를 return 가능

size 확인

dtype 확인

## Reshape

Reshape 

Reshape, -1 활용

random array 생성

3차원으로 늘리기

## Ravel

arr의 차원을 1로 바꿔줌  
나중에 배울 layer를 flatten 할 때 같은 기능이라 생각하면 됨 

arr.reshape(-1) 와 같음

## np.expand_dims()

안의 값은 유지하되 차원 수를 늘리고 싶을 때가 있음  
이럴 때 사용하는 것이 expand_dims  

## zeros & ones

0으로 채워진 numpy array를 만들 수 있음

In [4]:
zeros=np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
zeros=np.zeros(1)
zeros

array([0.])

In [7]:
ones=np.ones([10])
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
ones=np.ones([10,5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
ones*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [10]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [11]:
arr=np.arange(4,9)
arr

array([4, 5, 6, 7, 8])

In [13]:
arr=np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
arr=np.arange(9).reshape(3,3) #arange는 1차원으로 펼쳐서 반환

# Index

In [16]:
nums=[1,2,3,4,5]

In [18]:
nums[2:]

[3, 4, 5]

In [19]:
nums=[1,2,3,[1,2,3]]
nums

[1, 2, 3, [1, 2, 3]]

In [21]:
nums[3]

[1, 2, 3]

In [24]:
arr[1][2]

5

In [25]:
arr[1,2]

5

# Slicing

In [26]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [28]:
arr[1:][1:]

array([[6, 7, 8]])

In [29]:
arr[1:,1:]

array([[4, 5],
       [7, 8]])

## Boolean Indexing

In [32]:
data=np.random.randn(3,3)
data

array([[-1.04279406, -1.15949243,  0.68734966],
       [-0.42628399,  0.09578099, -1.08132704],
       [ 0.90202121,  0.14298934, -0.7223795 ]])

In [33]:
data<=0

array([[ True,  True, False],
       [ True, False,  True],
       [False, False,  True]])

In [36]:
data[data<=0]=1

In [37]:
data

array([[1.        , 1.        , 0.68734966],
       [1.        , 0.09578099, 1.        ],
       [0.90202121, 0.14298934, 1.        ]])

# Broadcast

tensorflow나 pytorch로 계산하면 broadcast의 개념도 잘 이해해야 함

broadcast는 연산 하려는 서로 다른 두개의 행렬의 shape가 같지 않고,  
한쪽의 차원이라도 같거나 또는 값의 갯수가 한 개 일 때  
이를 여러 복사를 하여 연산을 함

In [39]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
arr+3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
arr+np.array([1,2,3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

## Math Function

In [43]:
arr+10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [44]:
arr+5

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [45]:
arr+arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [46]:
np.add(arr,1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr+1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
np.multiply(arr,3)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [51]:
arr=np.random.randint(2,size=27).reshape(3,3,3)
arr_2=np.random.randint(2,size=9).reshape(3,3)


In [52]:
arr

array([[[0, 0, 0],
        [0, 1, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [1, 1, 1],
        [1, 1, 0]],

       [[0, 0, 1],
        [1, 1, 0],
        [1, 0, 0]]])

In [53]:
arr_2

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 1]])

In [54]:
arr+arr_2

array([[[0, 0, 0],
        [0, 1, 1],
        [0, 0, 1]],

       [[0, 0, 0],
        [1, 1, 2],
        [1, 1, 1]],

       [[0, 0, 1],
        [1, 1, 1],
        [1, 0, 1]]])

In [57]:
np.multiply(arr,arr_2)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 1],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [58]:
np.sum(arr)

10

In [59]:
np.sum(arr+arr_2)

16

In [60]:
np.max(arr+arr_2)

2

In [61]:
np.min(arr-arr_2)

-1

In [ ]:
arr+arr_2

In [ ]:
np.sum(arr+arr_2,0) #0차원 기준으로 두고 더해줌