In [1]:
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
#For reproducibility
torch.manual_seed(1)

np.random.rand(5)

In [10]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [14]:
np.random.seed(1)
np.random.rand(5)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01])

In [13]:
np.random.seed(1)
np.random.rand(5)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01])

In [19]:
torch.manual_seed(1)
torch.rand(5)

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293])

In [18]:
torch.manual_seed(1)
torch.rand(5)

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293])

In [27]:
print(torch.randint(10,size=(5,1)))
print(torch.randint(10,size=(3,2,1)))

tensor([[4],
        [4],
        [5],
        [8],
        [0]])
tensor([[[1],
         [3]],

        [[1],
         [4]],

        [[7],
         [8]]])


In [25]:
print(torch.randperm(10))
print(torch.randperm(5))

tensor([9, 5, 4, 8, 7, 3, 2, 6, 0, 1])
tensor([1, 0, 4, 2, 3])
