# Numpy Basic

In [2]:
import numpy as np

## data type

array의 dtype을 본다. 

In [5]:
arr=np.array([[1.,2.,3.],[1,2,3]])

In [6]:
arr.dtype

dtype('float64')

### astype()으로 datatype을 변환 가능

In [8]:
arr=arr.astype(np.int32)
arr

array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)

In [9]:
arr=np.array([[1.,2,3],[1,2,3]],dtype=np.uint8)
arr.dtype

dtype('uint8')

### uint8자료형
* 양수만 표현 가능
* 2^8개수 만큼 표현 가능
* 0~255

len(arr.shape) 를 통해서 차원의 갯수를 확인 할 수 있지만,  
아래와 같이 ndim을 통해 차원 수를 return 가능

In [10]:
len(arr.shape)

2

In [11]:
arr.shape

(2, 3)

size 확인

In [13]:
arr.size #2*3

6

dtype 확인

In [15]:
arr.dtype

dtype('uint8')

## Reshape

In [17]:
print(arr.shape)
print(arr.size)

(2, 3)
6


Reshape 

In [18]:
arr=arr.reshape([1,6])
arr.shape

(1, 6)

In [19]:
arr=np.array([[1,2,3],[1,2,3]])

In [20]:
arr.reshape([6]).shape

(6,)

Reshape, -1 활용

In [21]:
arr=arr.reshape(-1)
arr.shape

(6,)

In [22]:
arr=arr.reshape(-1,3)
arr.shape

(2, 3)

random array 생성

In [23]:
arr=np.random.randn(8,8)
arr.shape

(8, 8)

In [24]:
arr=arr.reshape([32,2])
arr.shape

(32, 2)

3차원으로 늘리기

In [26]:
arr.reshape(-1,2,1)
arr.shape

(32, 2)

In [27]:
arr

array([[-0.42326491, -0.30317276],
       [ 0.39626561,  0.37830951],
       [-2.86128236,  0.59563853],
       [ 1.10882201, -1.29331899],
       [-2.6572389 ,  1.41765379],
       [-0.21635059, -0.327475  ],
       [-1.06732787,  0.73722275],
       [ 1.60346315, -0.60203892],
       [ 1.02371307,  0.0117502 ],
       [-0.66233097,  1.38392289],
       [-1.20065187, -0.57343027],
       [ 2.760469  ,  1.80400221],
       [-1.71867481,  1.70239383],
       [-0.77284325, -0.63362342],
       [-0.90215785, -1.62480914],
       [ 1.00215553,  2.53291228],
       [-0.50781608, -0.29221897],
       [-1.03565532,  0.29223221],
       [-0.07092126,  0.39363713],
       [-0.65029956,  0.74810777],
       [-0.53710409, -0.3831669 ],
       [ 0.66285424, -1.54510884],
       [ 1.03252491,  1.01463671],
       [ 0.23648071,  0.71625095],
       [-0.7418027 , -0.92949635],
       [ 0.65016925, -0.70805609],
       [-2.43689303,  1.41973772],
       [ 0.89567343,  0.56768413],
       [ 0.16202829,

## Ravel
* 1차원으로 쫙 펼치기

In [37]:
arr=arr.ravel()
arr.shape

(64,)

arr의 차원을 1로 바꿔줌  
나중에 배울 **layer를 flatten** 할 때 같은 기능이라 생각하면 됨 

arr.reshape(-1) 와 같음

In [29]:
arr2=arr.reshape(-1)
arr2.shape

(64,)

In [30]:
arr.ravel()==arr.reshape(-1)


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## np.expand_dims()

안의 값은 유지하되 차원 수를 늘리고 싶을 때가 있음  
이럴 때 사용하는 것이 expand_dims  

In [38]:
arr.shape

(64,)

In [39]:
arr=np.expand_dims(arr,-1) #뒤에다가 1을 추가하고 싶으면 -1, 앞에 추가하고 싶으면 0
arr.shape


(64, 1)

In [42]:
arr=arr.ravel()
arr.shape

(64,)

In [43]:
arr=np.expand_dims(arr,0)
arr.shape

(1, 64)

## zeros & ones

0으로 채워진 numpy array를 만들 수 있음

In [4]:
zeros=np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
zeros=np.zeros(1)
zeros

array([0.])

In [7]:
ones=np.ones([10])
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
ones=np.ones([10,5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
ones*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [10]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [11]:
arr=np.arange(4,9)
arr

array([4, 5, 6, 7, 8])

In [13]:
arr=np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
arr=np.arange(9).reshape(3,3) #arange는 1차원으로 펼쳐서 반환

# Index

In [16]:
nums=[1,2,3,4,5]

In [18]:
nums[2:]

[3, 4, 5]

In [19]:
nums=[1,2,3,[1,2,3]]
nums

[1, 2, 3, [1, 2, 3]]

In [21]:
nums[3]

[1, 2, 3]

In [24]:
arr[1][2]

5

In [25]:
arr[1,2]

5

# Slicing

In [26]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [28]:
arr[1:][1:]

array([[6, 7, 8]])

In [29]:
arr[1:,1:]

array([[4, 5],
       [7, 8]])

## Boolean Indexing

In [32]:
data=np.random.randn(3,3)
data

array([[-1.04279406, -1.15949243,  0.68734966],
       [-0.42628399,  0.09578099, -1.08132704],
       [ 0.90202121,  0.14298934, -0.7223795 ]])

In [33]:
data<=0

array([[ True,  True, False],
       [ True, False,  True],
       [False, False,  True]])

In [36]:
data[data<=0]=1

In [37]:
data

array([[1.        , 1.        , 0.68734966],
       [1.        , 0.09578099, 1.        ],
       [0.90202121, 0.14298934, 1.        ]])

# Broadcast

tensorflow나 pytorch로 계산하면 broadcast의 개념도 잘 이해해야 함

broadcast는 연산 하려는 서로 다른 두개의 행렬의 shape가 같지 않고,  
한쪽의 차원이라도 같거나 또는 값의 갯수가 한 개 일 때  
이를 여러 복사를 하여 연산을 함

In [39]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
arr+3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
arr+np.array([1,2,3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

## Math Function

In [43]:
arr+10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [44]:
arr+5

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [45]:
arr+arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [46]:
np.add(arr,1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr+1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
np.multiply(arr,3)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [51]:
arr=np.random.randint(2,size=27).reshape(3,3,3)
arr_2=np.random.randint(2,size=9).reshape(3,3)


In [52]:
arr

array([[[0, 0, 0],
        [0, 1, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [1, 1, 1],
        [1, 1, 0]],

       [[0, 0, 1],
        [1, 1, 0],
        [1, 0, 0]]])

In [53]:
arr_2

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 1]])

In [54]:
arr+arr_2

array([[[0, 0, 0],
        [0, 1, 1],
        [0, 0, 1]],

       [[0, 0, 0],
        [1, 1, 2],
        [1, 1, 1]],

       [[0, 0, 1],
        [1, 1, 1],
        [1, 0, 1]]])

In [57]:
np.multiply(arr,arr_2)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 1],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [58]:
np.sum(arr)

10

In [59]:
np.sum(arr+arr_2)

16

In [60]:
np.max(arr+arr_2)

2

In [61]:
np.min(arr-arr_2)

-1

In [ ]:
arr+arr_2

In [ ]:
np.sum(arr+arr_2,0) #0차원 기준으로 두고 더해줌